apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: my-service-job
  name: my-service-job
spec:
  template:
    metadata:
      labels:
        job-name: my-service-job
    spec:
      restartPolicy: OnFailure
      containers:
      - image: alpine
        command: ["wget", "-O", "-", "http://my-service"]
        imagePullPolicy: IfNotPresent
        name: my-service-job
