clusterName: mfc
nodeGroup: master
esMajorVersion: 7
image: docker.elastic.co/elasticsearch/elasticsearch
imageTag: 7.1.0

# Setting for local environment
antiAffinity: "soft"

resources:
  requests:
    cpu: 100m
    memory: 512M
  limits:
    cpu: 1000m
    memory: 512M

esJavaOpts: "-Xmx128m -Xms128m"
