apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
        - name: my-container
          image: monopole/hello:1
          command:
            ["/hello", "--port=8080", "--enableRiskyFeature=$(ENABLE_RISKY)"]
          ports:
            - containerPort: 8080
          env:
            - name: ALT_GREETING
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: allGreeting
            - name: ENABLE_RISKY
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: enableRisky
